development:
  adapter: mysql2
  encoding: utf8
  database: fridayFlat_development
  host: localhost
  username: root
  password: 123

test:
  adapter: mysql2
  encoding: utf8
  database: fridayFlat_test
  host: localhost
  username: root
  password: 123
  
production:
  adapter: mysql2
  encoding: utf8
  database: dfridayFlat_production
  host: localhost
  username: root
  password: 123 